# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\dev\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\dev\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\tedti\Desktop\gunpowder

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\tedti\Desktop\gunpowder

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	C:\dev\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	C:\dev\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\dev\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	C:\dev\mingw64\bin\cmake.exe -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\dev\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	C:\dev\mingw64\bin\cmake.exe -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\dev\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	C:\dev\mingw64\bin\cmake.exe -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /d C:\Users\tedti\Desktop\gunpowder && $(CMAKE_COMMAND) -E cmake_progress_start C:\Users\tedti\Desktop\gunpowder\CMakeFiles C:\Users\tedti\Desktop\gunpowder\lib\flgl\\CMakeFiles\progress.marks
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\tedti\Desktop\gunpowder\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/flgl/CMakeFiles/GLAD.dir/rule:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/CMakeFiles/GLAD.dir/rule
.PHONY : lib/flgl/CMakeFiles/GLAD.dir/rule

# Convenience name for target.
GLAD: lib/flgl/CMakeFiles/GLAD.dir/rule
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\GLAD.dir\build.make lib/flgl/CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

# Convenience name for target.
lib/flgl/CMakeFiles/FLGL.dir/rule:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 lib/flgl/CMakeFiles/FLGL.dir/rule
.PHONY : lib/flgl/CMakeFiles/FLGL.dir/rule

# Convenience name for target.
FLGL: lib/flgl/CMakeFiles/FLGL.dir/rule
.PHONY : FLGL

# fast build rule for target.
FLGL/fast:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/build
.PHONY : FLGL/fast

lib/glad/src/glad.obj: lib/glad/src/glad.c.obj
.PHONY : lib/glad/src/glad.obj

# target to build an object file
lib/glad/src/glad.c.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\GLAD.dir\build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.obj
.PHONY : lib/glad/src/glad.c.obj

lib/glad/src/glad.i: lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.i

# target to preprocess a source file
lib/glad/src/glad.c.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\GLAD.dir\build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.c.i

lib/glad/src/glad.s: lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.s

# target to generate assembly for a file
lib/glad/src/glad.c.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\GLAD.dir\build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.c.s

src/Graphics.obj: src/Graphics.cpp.obj
.PHONY : src/Graphics.obj

# target to build an object file
src/Graphics.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.obj
.PHONY : src/Graphics.cpp.obj

src/Graphics.i: src/Graphics.cpp.i
.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s
.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Window.obj: src/Window.cpp.obj
.PHONY : src/Window.obj

# target to build an object file
src/Window.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.obj
.PHONY : src/Window.cpp.obj

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/flgl.obj: src/flgl.cpp.obj
.PHONY : src/flgl.obj

# target to build an object file
src/flgl.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.obj
.PHONY : src/flgl.cpp.obj

src/flgl.i: src/flgl.cpp.i
.PHONY : src/flgl.i

# target to preprocess a source file
src/flgl.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.i
.PHONY : src/flgl.cpp.i

src/flgl.s: src/flgl.cpp.s
.PHONY : src/flgl.s

# target to generate assembly for a file
src/flgl.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.s
.PHONY : src/flgl.cpp.s

src/gl_objs/Buffer.obj: src/gl_objs/Buffer.cpp.obj
.PHONY : src/gl_objs/Buffer.obj

# target to build an object file
src/gl_objs/Buffer.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.obj
.PHONY : src/gl_objs/Buffer.cpp.obj

src/gl_objs/Buffer.i: src/gl_objs/Buffer.cpp.i
.PHONY : src/gl_objs/Buffer.i

# target to preprocess a source file
src/gl_objs/Buffer.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.i
.PHONY : src/gl_objs/Buffer.cpp.i

src/gl_objs/Buffer.s: src/gl_objs/Buffer.cpp.s
.PHONY : src/gl_objs/Buffer.s

# target to generate assembly for a file
src/gl_objs/Buffer.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.s
.PHONY : src/gl_objs/Buffer.cpp.s

src/gl_objs/Framebuffer.obj: src/gl_objs/Framebuffer.cpp.obj
.PHONY : src/gl_objs/Framebuffer.obj

# target to build an object file
src/gl_objs/Framebuffer.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.obj
.PHONY : src/gl_objs/Framebuffer.cpp.obj

src/gl_objs/Framebuffer.i: src/gl_objs/Framebuffer.cpp.i
.PHONY : src/gl_objs/Framebuffer.i

# target to preprocess a source file
src/gl_objs/Framebuffer.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.i
.PHONY : src/gl_objs/Framebuffer.cpp.i

src/gl_objs/Framebuffer.s: src/gl_objs/Framebuffer.cpp.s
.PHONY : src/gl_objs/Framebuffer.s

# target to generate assembly for a file
src/gl_objs/Framebuffer.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.s
.PHONY : src/gl_objs/Framebuffer.cpp.s

src/gl_objs/FramebufferRGBZ.obj: src/gl_objs/FramebufferRGBZ.cpp.obj
.PHONY : src/gl_objs/FramebufferRGBZ.obj

# target to build an object file
src/gl_objs/FramebufferRGBZ.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.obj
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.obj

src/gl_objs/FramebufferRGBZ.i: src/gl_objs/FramebufferRGBZ.cpp.i
.PHONY : src/gl_objs/FramebufferRGBZ.i

# target to preprocess a source file
src/gl_objs/FramebufferRGBZ.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.i
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.i

src/gl_objs/FramebufferRGBZ.s: src/gl_objs/FramebufferRGBZ.cpp.s
.PHONY : src/gl_objs/FramebufferRGBZ.s

# target to generate assembly for a file
src/gl_objs/FramebufferRGBZ.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.s
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.s

src/gl_objs/GL_Object.obj: src/gl_objs/GL_Object.cpp.obj
.PHONY : src/gl_objs/GL_Object.obj

# target to build an object file
src/gl_objs/GL_Object.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.obj
.PHONY : src/gl_objs/GL_Object.cpp.obj

src/gl_objs/GL_Object.i: src/gl_objs/GL_Object.cpp.i
.PHONY : src/gl_objs/GL_Object.i

# target to preprocess a source file
src/gl_objs/GL_Object.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.i
.PHONY : src/gl_objs/GL_Object.cpp.i

src/gl_objs/GL_Object.s: src/gl_objs/GL_Object.cpp.s
.PHONY : src/gl_objs/GL_Object.s

# target to generate assembly for a file
src/gl_objs/GL_Object.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.s
.PHONY : src/gl_objs/GL_Object.cpp.s

src/gl_objs/Renderbuffer.obj: src/gl_objs/Renderbuffer.cpp.obj
.PHONY : src/gl_objs/Renderbuffer.obj

# target to build an object file
src/gl_objs/Renderbuffer.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.obj
.PHONY : src/gl_objs/Renderbuffer.cpp.obj

src/gl_objs/Renderbuffer.i: src/gl_objs/Renderbuffer.cpp.i
.PHONY : src/gl_objs/Renderbuffer.i

# target to preprocess a source file
src/gl_objs/Renderbuffer.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.i
.PHONY : src/gl_objs/Renderbuffer.cpp.i

src/gl_objs/Renderbuffer.s: src/gl_objs/Renderbuffer.cpp.s
.PHONY : src/gl_objs/Renderbuffer.s

# target to generate assembly for a file
src/gl_objs/Renderbuffer.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.s
.PHONY : src/gl_objs/Renderbuffer.cpp.s

src/gl_objs/Shader.obj: src/gl_objs/Shader.cpp.obj
.PHONY : src/gl_objs/Shader.obj

# target to build an object file
src/gl_objs/Shader.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.obj
.PHONY : src/gl_objs/Shader.cpp.obj

src/gl_objs/Shader.i: src/gl_objs/Shader.cpp.i
.PHONY : src/gl_objs/Shader.i

# target to preprocess a source file
src/gl_objs/Shader.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.i
.PHONY : src/gl_objs/Shader.cpp.i

src/gl_objs/Shader.s: src/gl_objs/Shader.cpp.s
.PHONY : src/gl_objs/Shader.s

# target to generate assembly for a file
src/gl_objs/Shader.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.s
.PHONY : src/gl_objs/Shader.cpp.s

src/gl_objs/Texture.obj: src/gl_objs/Texture.cpp.obj
.PHONY : src/gl_objs/Texture.obj

# target to build an object file
src/gl_objs/Texture.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.obj
.PHONY : src/gl_objs/Texture.cpp.obj

src/gl_objs/Texture.i: src/gl_objs/Texture.cpp.i
.PHONY : src/gl_objs/Texture.i

# target to preprocess a source file
src/gl_objs/Texture.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.i
.PHONY : src/gl_objs/Texture.cpp.i

src/gl_objs/Texture.s: src/gl_objs/Texture.cpp.s
.PHONY : src/gl_objs/Texture.s

# target to generate assembly for a file
src/gl_objs/Texture.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.s
.PHONY : src/gl_objs/Texture.cpp.s

src/gl_objs/VertexArray.obj: src/gl_objs/VertexArray.cpp.obj
.PHONY : src/gl_objs/VertexArray.obj

# target to build an object file
src/gl_objs/VertexArray.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.obj
.PHONY : src/gl_objs/VertexArray.cpp.obj

src/gl_objs/VertexArray.i: src/gl_objs/VertexArray.cpp.i
.PHONY : src/gl_objs/VertexArray.i

# target to preprocess a source file
src/gl_objs/VertexArray.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.i
.PHONY : src/gl_objs/VertexArray.cpp.i

src/gl_objs/VertexArray.s: src/gl_objs/VertexArray.cpp.s
.PHONY : src/gl_objs/VertexArray.s

# target to generate assembly for a file
src/gl_objs/VertexArray.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.s
.PHONY : src/gl_objs/VertexArray.cpp.s

src/gl_objs/VertexBuffer.obj: src/gl_objs/VertexBuffer.cpp.obj
.PHONY : src/gl_objs/VertexBuffer.obj

# target to build an object file
src/gl_objs/VertexBuffer.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.obj
.PHONY : src/gl_objs/VertexBuffer.cpp.obj

src/gl_objs/VertexBuffer.i: src/gl_objs/VertexBuffer.cpp.i
.PHONY : src/gl_objs/VertexBuffer.i

# target to preprocess a source file
src/gl_objs/VertexBuffer.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.i
.PHONY : src/gl_objs/VertexBuffer.cpp.i

src/gl_objs/VertexBuffer.s: src/gl_objs/VertexBuffer.cpp.s
.PHONY : src/gl_objs/VertexBuffer.s

# target to generate assembly for a file
src/gl_objs/VertexBuffer.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.s
.PHONY : src/gl_objs/VertexBuffer.cpp.s

src/tools/Camera.obj: src/tools/Camera.cpp.obj
.PHONY : src/tools/Camera.obj

# target to build an object file
src/tools/Camera.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.obj
.PHONY : src/tools/Camera.cpp.obj

src/tools/Camera.i: src/tools/Camera.cpp.i
.PHONY : src/tools/Camera.i

# target to preprocess a source file
src/tools/Camera.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.i
.PHONY : src/tools/Camera.cpp.i

src/tools/Camera.s: src/tools/Camera.cpp.s
.PHONY : src/tools/Camera.s

# target to generate assembly for a file
src/tools/Camera.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.s
.PHONY : src/tools/Camera.cpp.s

src/tools/DefaultMeshes.obj: src/tools/DefaultMeshes.cpp.obj
.PHONY : src/tools/DefaultMeshes.obj

# target to build an object file
src/tools/DefaultMeshes.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.obj
.PHONY : src/tools/DefaultMeshes.cpp.obj

src/tools/DefaultMeshes.i: src/tools/DefaultMeshes.cpp.i
.PHONY : src/tools/DefaultMeshes.i

# target to preprocess a source file
src/tools/DefaultMeshes.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.i
.PHONY : src/tools/DefaultMeshes.cpp.i

src/tools/DefaultMeshes.s: src/tools/DefaultMeshes.cpp.s
.PHONY : src/tools/DefaultMeshes.s

# target to generate assembly for a file
src/tools/DefaultMeshes.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.s
.PHONY : src/tools/DefaultMeshes.cpp.s

src/tools/flgl_math.obj: src/tools/flgl_math.cpp.obj
.PHONY : src/tools/flgl_math.obj

# target to build an object file
src/tools/flgl_math.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.obj
.PHONY : src/tools/flgl_math.cpp.obj

src/tools/flgl_math.i: src/tools/flgl_math.cpp.i
.PHONY : src/tools/flgl_math.i

# target to preprocess a source file
src/tools/flgl_math.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.i
.PHONY : src/tools/flgl_math.cpp.i

src/tools/flgl_math.s: src/tools/flgl_math.cpp.s
.PHONY : src/tools/flgl_math.s

# target to generate assembly for a file
src/tools/flgl_math.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.s
.PHONY : src/tools/flgl_math.cpp.s

src/util/log.obj: src/util/log.cpp.obj
.PHONY : src/util/log.obj

# target to build an object file
src/util/log.cpp.obj:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.obj
.PHONY : src/util/log.cpp.obj

src/util/log.i: src/util/log.cpp.i
.PHONY : src/util/log.i

# target to preprocess a source file
src/util/log.cpp.i:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.i
.PHONY : src/util/log.cpp.i

src/util/log.s: src/util/log.cpp.s
.PHONY : src/util/log.s

# target to generate assembly for a file
src/util/log.cpp.s:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(MAKE) $(MAKESILENT) -f lib\flgl\CMakeFiles\FLGL.dir\build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.s
.PHONY : src/util/log.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... install
	@echo ... install/local
	@echo ... install/strip
	@echo ... list_install_components
	@echo ... rebuild_cache
	@echo ... FLGL
	@echo ... GLAD
	@echo ... lib/glad/src/glad.obj
	@echo ... lib/glad/src/glad.i
	@echo ... lib/glad/src/glad.s
	@echo ... src/Graphics.obj
	@echo ... src/Graphics.i
	@echo ... src/Graphics.s
	@echo ... src/Window.obj
	@echo ... src/Window.i
	@echo ... src/Window.s
	@echo ... src/flgl.obj
	@echo ... src/flgl.i
	@echo ... src/flgl.s
	@echo ... src/gl_objs/Buffer.obj
	@echo ... src/gl_objs/Buffer.i
	@echo ... src/gl_objs/Buffer.s
	@echo ... src/gl_objs/Framebuffer.obj
	@echo ... src/gl_objs/Framebuffer.i
	@echo ... src/gl_objs/Framebuffer.s
	@echo ... src/gl_objs/FramebufferRGBZ.obj
	@echo ... src/gl_objs/FramebufferRGBZ.i
	@echo ... src/gl_objs/FramebufferRGBZ.s
	@echo ... src/gl_objs/GL_Object.obj
	@echo ... src/gl_objs/GL_Object.i
	@echo ... src/gl_objs/GL_Object.s
	@echo ... src/gl_objs/Renderbuffer.obj
	@echo ... src/gl_objs/Renderbuffer.i
	@echo ... src/gl_objs/Renderbuffer.s
	@echo ... src/gl_objs/Shader.obj
	@echo ... src/gl_objs/Shader.i
	@echo ... src/gl_objs/Shader.s
	@echo ... src/gl_objs/Texture.obj
	@echo ... src/gl_objs/Texture.i
	@echo ... src/gl_objs/Texture.s
	@echo ... src/gl_objs/VertexArray.obj
	@echo ... src/gl_objs/VertexArray.i
	@echo ... src/gl_objs/VertexArray.s
	@echo ... src/gl_objs/VertexBuffer.obj
	@echo ... src/gl_objs/VertexBuffer.i
	@echo ... src/gl_objs/VertexBuffer.s
	@echo ... src/tools/Camera.obj
	@echo ... src/tools/Camera.i
	@echo ... src/tools/Camera.s
	@echo ... src/tools/DefaultMeshes.obj
	@echo ... src/tools/DefaultMeshes.i
	@echo ... src/tools/DefaultMeshes.s
	@echo ... src/tools/flgl_math.obj
	@echo ... src/tools/flgl_math.i
	@echo ... src/tools/flgl_math.s
	@echo ... src/util/log.obj
	@echo ... src/util/log.i
	@echo ... src/util/log.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /d C:\Users\tedti\Desktop\gunpowder && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

