# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/frankcollebrusco/dev/flgl_testing

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/frankcollebrusco/dev/flgl_testing

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/homebrew/Cellar/cmake/3.27.7/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	cd /Users/frankcollebrusco/dev/flgl_testing && $(CMAKE_COMMAND) -E cmake_progress_start /Users/frankcollebrusco/dev/flgl_testing/CMakeFiles /Users/frankcollebrusco/dev/flgl_testing/lib/flgl//CMakeFiles/progress.marks
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/frankcollebrusco/dev/flgl_testing/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
lib/flgl/CMakeFiles/GLAD.dir/rule:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/CMakeFiles/GLAD.dir/rule
.PHONY : lib/flgl/CMakeFiles/GLAD.dir/rule

# Convenience name for target.
GLAD: lib/flgl/CMakeFiles/GLAD.dir/rule
.PHONY : GLAD

# fast build rule for target.
GLAD/fast:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/GLAD.dir/build.make lib/flgl/CMakeFiles/GLAD.dir/build
.PHONY : GLAD/fast

# Convenience name for target.
lib/flgl/CMakeFiles/FLGL.dir/rule:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lib/flgl/CMakeFiles/FLGL.dir/rule
.PHONY : lib/flgl/CMakeFiles/FLGL.dir/rule

# Convenience name for target.
FLGL: lib/flgl/CMakeFiles/FLGL.dir/rule
.PHONY : FLGL

# fast build rule for target.
FLGL/fast:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/build
.PHONY : FLGL/fast

lib/glad/src/glad.o: lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.o

# target to build an object file
lib/glad/src/glad.c.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/GLAD.dir/build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.o
.PHONY : lib/glad/src/glad.c.o

lib/glad/src/glad.i: lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.i

# target to preprocess a source file
lib/glad/src/glad.c.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/GLAD.dir/build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.i
.PHONY : lib/glad/src/glad.c.i

lib/glad/src/glad.s: lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.s

# target to generate assembly for a file
lib/glad/src/glad.c.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/GLAD.dir/build.make lib/flgl/CMakeFiles/GLAD.dir/lib/glad/src/glad.c.s
.PHONY : lib/glad/src/glad.c.s

src/Graphics.o: src/Graphics.cpp.o
.PHONY : src/Graphics.o

# target to build an object file
src/Graphics.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.o
.PHONY : src/Graphics.cpp.o

src/Graphics.i: src/Graphics.cpp.i
.PHONY : src/Graphics.i

# target to preprocess a source file
src/Graphics.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.i
.PHONY : src/Graphics.cpp.i

src/Graphics.s: src/Graphics.cpp.s
.PHONY : src/Graphics.s

# target to generate assembly for a file
src/Graphics.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Graphics.cpp.s
.PHONY : src/Graphics.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/flgl.o: src/flgl.cpp.o
.PHONY : src/flgl.o

# target to build an object file
src/flgl.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.o
.PHONY : src/flgl.cpp.o

src/flgl.i: src/flgl.cpp.i
.PHONY : src/flgl.i

# target to preprocess a source file
src/flgl.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.i
.PHONY : src/flgl.cpp.i

src/flgl.s: src/flgl.cpp.s
.PHONY : src/flgl.s

# target to generate assembly for a file
src/flgl.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/flgl.cpp.s
.PHONY : src/flgl.cpp.s

src/gl_objs/Buffer.o: src/gl_objs/Buffer.cpp.o
.PHONY : src/gl_objs/Buffer.o

# target to build an object file
src/gl_objs/Buffer.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.o
.PHONY : src/gl_objs/Buffer.cpp.o

src/gl_objs/Buffer.i: src/gl_objs/Buffer.cpp.i
.PHONY : src/gl_objs/Buffer.i

# target to preprocess a source file
src/gl_objs/Buffer.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.i
.PHONY : src/gl_objs/Buffer.cpp.i

src/gl_objs/Buffer.s: src/gl_objs/Buffer.cpp.s
.PHONY : src/gl_objs/Buffer.s

# target to generate assembly for a file
src/gl_objs/Buffer.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Buffer.cpp.s
.PHONY : src/gl_objs/Buffer.cpp.s

src/gl_objs/Framebuffer.o: src/gl_objs/Framebuffer.cpp.o
.PHONY : src/gl_objs/Framebuffer.o

# target to build an object file
src/gl_objs/Framebuffer.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.o
.PHONY : src/gl_objs/Framebuffer.cpp.o

src/gl_objs/Framebuffer.i: src/gl_objs/Framebuffer.cpp.i
.PHONY : src/gl_objs/Framebuffer.i

# target to preprocess a source file
src/gl_objs/Framebuffer.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.i
.PHONY : src/gl_objs/Framebuffer.cpp.i

src/gl_objs/Framebuffer.s: src/gl_objs/Framebuffer.cpp.s
.PHONY : src/gl_objs/Framebuffer.s

# target to generate assembly for a file
src/gl_objs/Framebuffer.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Framebuffer.cpp.s
.PHONY : src/gl_objs/Framebuffer.cpp.s

src/gl_objs/FramebufferRGBZ.o: src/gl_objs/FramebufferRGBZ.cpp.o
.PHONY : src/gl_objs/FramebufferRGBZ.o

# target to build an object file
src/gl_objs/FramebufferRGBZ.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.o
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.o

src/gl_objs/FramebufferRGBZ.i: src/gl_objs/FramebufferRGBZ.cpp.i
.PHONY : src/gl_objs/FramebufferRGBZ.i

# target to preprocess a source file
src/gl_objs/FramebufferRGBZ.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.i
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.i

src/gl_objs/FramebufferRGBZ.s: src/gl_objs/FramebufferRGBZ.cpp.s
.PHONY : src/gl_objs/FramebufferRGBZ.s

# target to generate assembly for a file
src/gl_objs/FramebufferRGBZ.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/FramebufferRGBZ.cpp.s
.PHONY : src/gl_objs/FramebufferRGBZ.cpp.s

src/gl_objs/GL_Object.o: src/gl_objs/GL_Object.cpp.o
.PHONY : src/gl_objs/GL_Object.o

# target to build an object file
src/gl_objs/GL_Object.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.o
.PHONY : src/gl_objs/GL_Object.cpp.o

src/gl_objs/GL_Object.i: src/gl_objs/GL_Object.cpp.i
.PHONY : src/gl_objs/GL_Object.i

# target to preprocess a source file
src/gl_objs/GL_Object.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.i
.PHONY : src/gl_objs/GL_Object.cpp.i

src/gl_objs/GL_Object.s: src/gl_objs/GL_Object.cpp.s
.PHONY : src/gl_objs/GL_Object.s

# target to generate assembly for a file
src/gl_objs/GL_Object.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/GL_Object.cpp.s
.PHONY : src/gl_objs/GL_Object.cpp.s

src/gl_objs/Renderbuffer.o: src/gl_objs/Renderbuffer.cpp.o
.PHONY : src/gl_objs/Renderbuffer.o

# target to build an object file
src/gl_objs/Renderbuffer.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.o
.PHONY : src/gl_objs/Renderbuffer.cpp.o

src/gl_objs/Renderbuffer.i: src/gl_objs/Renderbuffer.cpp.i
.PHONY : src/gl_objs/Renderbuffer.i

# target to preprocess a source file
src/gl_objs/Renderbuffer.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.i
.PHONY : src/gl_objs/Renderbuffer.cpp.i

src/gl_objs/Renderbuffer.s: src/gl_objs/Renderbuffer.cpp.s
.PHONY : src/gl_objs/Renderbuffer.s

# target to generate assembly for a file
src/gl_objs/Renderbuffer.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Renderbuffer.cpp.s
.PHONY : src/gl_objs/Renderbuffer.cpp.s

src/gl_objs/Shader.o: src/gl_objs/Shader.cpp.o
.PHONY : src/gl_objs/Shader.o

# target to build an object file
src/gl_objs/Shader.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.o
.PHONY : src/gl_objs/Shader.cpp.o

src/gl_objs/Shader.i: src/gl_objs/Shader.cpp.i
.PHONY : src/gl_objs/Shader.i

# target to preprocess a source file
src/gl_objs/Shader.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.i
.PHONY : src/gl_objs/Shader.cpp.i

src/gl_objs/Shader.s: src/gl_objs/Shader.cpp.s
.PHONY : src/gl_objs/Shader.s

# target to generate assembly for a file
src/gl_objs/Shader.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Shader.cpp.s
.PHONY : src/gl_objs/Shader.cpp.s

src/gl_objs/Texture.o: src/gl_objs/Texture.cpp.o
.PHONY : src/gl_objs/Texture.o

# target to build an object file
src/gl_objs/Texture.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.o
.PHONY : src/gl_objs/Texture.cpp.o

src/gl_objs/Texture.i: src/gl_objs/Texture.cpp.i
.PHONY : src/gl_objs/Texture.i

# target to preprocess a source file
src/gl_objs/Texture.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.i
.PHONY : src/gl_objs/Texture.cpp.i

src/gl_objs/Texture.s: src/gl_objs/Texture.cpp.s
.PHONY : src/gl_objs/Texture.s

# target to generate assembly for a file
src/gl_objs/Texture.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/Texture.cpp.s
.PHONY : src/gl_objs/Texture.cpp.s

src/gl_objs/VertexArray.o: src/gl_objs/VertexArray.cpp.o
.PHONY : src/gl_objs/VertexArray.o

# target to build an object file
src/gl_objs/VertexArray.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.o
.PHONY : src/gl_objs/VertexArray.cpp.o

src/gl_objs/VertexArray.i: src/gl_objs/VertexArray.cpp.i
.PHONY : src/gl_objs/VertexArray.i

# target to preprocess a source file
src/gl_objs/VertexArray.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.i
.PHONY : src/gl_objs/VertexArray.cpp.i

src/gl_objs/VertexArray.s: src/gl_objs/VertexArray.cpp.s
.PHONY : src/gl_objs/VertexArray.s

# target to generate assembly for a file
src/gl_objs/VertexArray.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexArray.cpp.s
.PHONY : src/gl_objs/VertexArray.cpp.s

src/gl_objs/VertexBuffer.o: src/gl_objs/VertexBuffer.cpp.o
.PHONY : src/gl_objs/VertexBuffer.o

# target to build an object file
src/gl_objs/VertexBuffer.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.o
.PHONY : src/gl_objs/VertexBuffer.cpp.o

src/gl_objs/VertexBuffer.i: src/gl_objs/VertexBuffer.cpp.i
.PHONY : src/gl_objs/VertexBuffer.i

# target to preprocess a source file
src/gl_objs/VertexBuffer.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.i
.PHONY : src/gl_objs/VertexBuffer.cpp.i

src/gl_objs/VertexBuffer.s: src/gl_objs/VertexBuffer.cpp.s
.PHONY : src/gl_objs/VertexBuffer.s

# target to generate assembly for a file
src/gl_objs/VertexBuffer.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/gl_objs/VertexBuffer.cpp.s
.PHONY : src/gl_objs/VertexBuffer.cpp.s

src/tools/Camera.o: src/tools/Camera.cpp.o
.PHONY : src/tools/Camera.o

# target to build an object file
src/tools/Camera.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.o
.PHONY : src/tools/Camera.cpp.o

src/tools/Camera.i: src/tools/Camera.cpp.i
.PHONY : src/tools/Camera.i

# target to preprocess a source file
src/tools/Camera.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.i
.PHONY : src/tools/Camera.cpp.i

src/tools/Camera.s: src/tools/Camera.cpp.s
.PHONY : src/tools/Camera.s

# target to generate assembly for a file
src/tools/Camera.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/Camera.cpp.s
.PHONY : src/tools/Camera.cpp.s

src/tools/DefaultMeshes.o: src/tools/DefaultMeshes.cpp.o
.PHONY : src/tools/DefaultMeshes.o

# target to build an object file
src/tools/DefaultMeshes.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.o
.PHONY : src/tools/DefaultMeshes.cpp.o

src/tools/DefaultMeshes.i: src/tools/DefaultMeshes.cpp.i
.PHONY : src/tools/DefaultMeshes.i

# target to preprocess a source file
src/tools/DefaultMeshes.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.i
.PHONY : src/tools/DefaultMeshes.cpp.i

src/tools/DefaultMeshes.s: src/tools/DefaultMeshes.cpp.s
.PHONY : src/tools/DefaultMeshes.s

# target to generate assembly for a file
src/tools/DefaultMeshes.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/DefaultMeshes.cpp.s
.PHONY : src/tools/DefaultMeshes.cpp.s

src/tools/flgl_math.o: src/tools/flgl_math.cpp.o
.PHONY : src/tools/flgl_math.o

# target to build an object file
src/tools/flgl_math.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.o
.PHONY : src/tools/flgl_math.cpp.o

src/tools/flgl_math.i: src/tools/flgl_math.cpp.i
.PHONY : src/tools/flgl_math.i

# target to preprocess a source file
src/tools/flgl_math.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.i
.PHONY : src/tools/flgl_math.cpp.i

src/tools/flgl_math.s: src/tools/flgl_math.cpp.s
.PHONY : src/tools/flgl_math.s

# target to generate assembly for a file
src/tools/flgl_math.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/tools/flgl_math.cpp.s
.PHONY : src/tools/flgl_math.cpp.s

src/util/log.o: src/util/log.cpp.o
.PHONY : src/util/log.o

# target to build an object file
src/util/log.cpp.o:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.o
.PHONY : src/util/log.cpp.o

src/util/log.i: src/util/log.cpp.i
.PHONY : src/util/log.i

# target to preprocess a source file
src/util/log.cpp.i:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.i
.PHONY : src/util/log.cpp.i

src/util/log.s: src/util/log.cpp.s
.PHONY : src/util/log.s

# target to generate assembly for a file
src/util/log.cpp.s:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(MAKE) $(MAKESILENT) -f lib/flgl/CMakeFiles/FLGL.dir/build.make lib/flgl/CMakeFiles/FLGL.dir/src/util/log.cpp.s
.PHONY : src/util/log.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... FLGL"
	@echo "... GLAD"
	@echo "... lib/glad/src/glad.o"
	@echo "... lib/glad/src/glad.i"
	@echo "... lib/glad/src/glad.s"
	@echo "... src/Graphics.o"
	@echo "... src/Graphics.i"
	@echo "... src/Graphics.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/flgl.o"
	@echo "... src/flgl.i"
	@echo "... src/flgl.s"
	@echo "... src/gl_objs/Buffer.o"
	@echo "... src/gl_objs/Buffer.i"
	@echo "... src/gl_objs/Buffer.s"
	@echo "... src/gl_objs/Framebuffer.o"
	@echo "... src/gl_objs/Framebuffer.i"
	@echo "... src/gl_objs/Framebuffer.s"
	@echo "... src/gl_objs/FramebufferRGBZ.o"
	@echo "... src/gl_objs/FramebufferRGBZ.i"
	@echo "... src/gl_objs/FramebufferRGBZ.s"
	@echo "... src/gl_objs/GL_Object.o"
	@echo "... src/gl_objs/GL_Object.i"
	@echo "... src/gl_objs/GL_Object.s"
	@echo "... src/gl_objs/Renderbuffer.o"
	@echo "... src/gl_objs/Renderbuffer.i"
	@echo "... src/gl_objs/Renderbuffer.s"
	@echo "... src/gl_objs/Shader.o"
	@echo "... src/gl_objs/Shader.i"
	@echo "... src/gl_objs/Shader.s"
	@echo "... src/gl_objs/Texture.o"
	@echo "... src/gl_objs/Texture.i"
	@echo "... src/gl_objs/Texture.s"
	@echo "... src/gl_objs/VertexArray.o"
	@echo "... src/gl_objs/VertexArray.i"
	@echo "... src/gl_objs/VertexArray.s"
	@echo "... src/gl_objs/VertexBuffer.o"
	@echo "... src/gl_objs/VertexBuffer.i"
	@echo "... src/gl_objs/VertexBuffer.s"
	@echo "... src/tools/Camera.o"
	@echo "... src/tools/Camera.i"
	@echo "... src/tools/Camera.s"
	@echo "... src/tools/DefaultMeshes.o"
	@echo "... src/tools/DefaultMeshes.i"
	@echo "... src/tools/DefaultMeshes.s"
	@echo "... src/tools/flgl_math.o"
	@echo "... src/tools/flgl_math.i"
	@echo "... src/tools/flgl_math.s"
	@echo "... src/util/log.o"
	@echo "... src/util/log.i"
	@echo "... src/util/log.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /Users/frankcollebrusco/dev/flgl_testing && $(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

